# Generated by Django 3.2.6 on 2021-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0003_auto_20210909_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='message',
            field=models.TextField(),
        ),
    ]
