# Generated by Django 3.2.6 on 2021-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0007_original_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='print_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='print_image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
