# Generated by Django 3.2.6 on 2021-09-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
