# Generated by Django 3.2.6 on 2021-09-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0010_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Original',
            new_name='Original_product',
        ),
        migrations.DeleteModel(
            name='Print',
        ),
    ]
