# Generated by Django 3.2.6 on 2021-09-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0017_cart_cartproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
