# Generated by Django 3.2.6 on 2021-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0019_cart_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
