# Generated by Django 3.2.6 on 2021-09-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0021_alter_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
