# Generated by Django 3.2.6 on 2021-09-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0030_auto_20210917_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
