# Generated by Django 3.2.6 on 2021-09-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0031_shippingaddress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='status',
        ),
    ]
