# Generated by Django 3.2.6 on 2021-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0034_auto_20210918_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
