# Generated by Django 3.2.6 on 2021-09-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0035_auto_20210918_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandala_circle.orderitem'),
        ),
    ]
