# Generated by Django 3.2.6 on 2021-09-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0036_alter_shippingaddress_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='quantity',
        ),
    ]
