# Generated by Django 3.2.6 on 2021-09-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0037_remove_shippingaddress_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='orderDetail',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
