# Generated by Django 3.2.6 on 2021-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0039_orderdetail_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('completed', 'completed')], default='Incomplete', max_length=200, null=True),
        ),
    ]
