# Generated by Django 3.2.6 on 2021-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0040_auto_20210920_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('completed', 'completed'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=200, null=True),
        ),
    ]
