# Generated by Django 3.2.6 on 2021-09-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0043_remove_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
