# Generated by Django 3.2.6 on 2021-09-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0044_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='orderDetail',
        ),
    ]
