# Generated by Django 3.2.6 on 2021-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0045_auto_20210921_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
