# Generated by Django 3.2.6 on 2021-09-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0057_auto_20210921_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_status',
            field=models.BooleanField(default=False),
        ),
    ]
