# Generated by Django 3.2.6 on 2021-09-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0058_orderitem_delivered_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
