# Generated by Django 3.2.6 on 2021-09-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0059_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandala_circle.product'),
        ),
    ]
