# Generated by Django 3.2.6 on 2021-09-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_circle', '0060_shippingaddress_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='product',
        ),
    ]
