# Generated by Django 3.2.6 on 2021-09-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20210909_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Original',
        ),
        migrations.DeleteModel(
            name='Print',
        ),
    ]
